apiVersion: v1
kind: Service
metadata:
  labels:
    component: monkey
  name: custom-app 
  namespace: monkey
spec:
  ports:
    - name: custom
      port: 8080
      nodePort: 32005 
      targetPort: 8080
      protocol: TCP
  selector:
    component: monkey
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    component: monkey
  name: custom-app 
  namespace: monkey
spec:
  replicas: 5
  selector:
    matchLabels:
      component: monkey
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: monkey
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - jedha-admin-1
      containers:
      - image: vip-intOAM:5001/custom-app:v1  
        imagePullPolicy: Always
        name: custom-app 
        ports:
        - containerPort: 8080 
          name: http
          protocol: TCP
        volumeMounts:
          - name: ramfs-vol  
            mountPath: ramfs 
      volumes:
       - name: ramfs-vol
         emptyDir:
           medium: "Memory"
