apiVersion: v1
kind: Service
metadata:
  labels:
    component: monkey
  name: monkey-man-svc
  namespace: monkey
spec:
  ports:
    - name: nginx-port
      nodePort: 31500
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    component: monkey
  type: NodePort
