#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: monkey-user
#  namespace: monkey
#---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeMonkeyRole
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs: ["get", "watch", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeMonkeyRoleBinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kubeMonkeyRole
  apiGroup: rbac.authorization.k8s.io
